# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19--eneK0Ntj7XXOCSoJESF8mqEuYg0Ql
"""

import json

building = ['Basketball ground', 'Masjid Ground', 'EE Ground', 'EE Building', 'CS Building', 'New Building', 'Futsal Court', 'FYP Lab', 'Job Fair']
directions = [
    'take the first left',
    'ASK ALLAH',
    'take the second right',
    'take the second right',
    'take the second left',
    'take the first left, keep going straight until you reach the basketball court then turn right. The building will be to your left.',
    'take the first left, keep going straight until you reach the basketball court then turn right. Take the first left and go straight until you reach the Futsal court.',
    'CS-BLOCK, 1st FLOOR to the Right',
    'take the second right'
]

data = []
# print(len(comp_list),len(comp_description))
for i, buildname in enumerate(building):
    data.append(
    {
        "tag": f"{buildname}_direction",
        "patterns": [
            f"Where is {buildname}?",
            f"Where can I find {buildname}?",
            f"Could you tell me where {buildname} is located?",
            f"I'm trying to locate {buildname}, do you know where it is?",
            f"Do you happen to know the location of {buildname}?",
            f"Excuse me, could you point me in the direction of {buildname}?",
            f"Would you happen to have any information on the location of {buildname}?",
            f"I'm lost, can you help me find {buildname}?",
            f"I need to get to {buildname}, where should I go?",
            f"Can you please provide directions to {buildname}?",
            f"Which way is {buildname}?",
            f"I'm looking for {buildname}, could you assist me with its location?",
            f"Is {buildname} nearby? If so, could you tell me how to get there?",
            f"I'm searching for {buildname}, any idea where it could be?",
            f"Please could you tell me the location of {buildname}?",
            f"I'm not familiar with this area, could you tell me where {buildname} is?",
            f"Can you help me locate {buildname}, please?",
            f"Excuse me, I'm trying to find {buildname}, where should I go?",
            f"I'm hoping you could help me, where is {buildname}?",
            f"Hey, do you know where I can find {buildname}?",
            f"I'm on a hunt for {buildname}, any idea where it is?",
            f"Where exactly is {buildname} located?",
            f"Please tell me the location of {buildname}.",
            f"Could you point me towards {buildname}, please?",
            f"I can't seem to find {buildname}, do you know where it is?",
            f"I'm looking for {buildname}, any assistance would be greatly appreciated.",
            f"Do you have any information on the location of {buildname}?",
            f"I'm trying to locate {buildname}, any idea where I should look?",
            f"Which direction should I go to get to {buildname}?",
            f"I'm lost and I need to find {buildname}, could you help me please?",
            f"I need to know where {buildname} is located, could you tell me please?",
            f"Can you provide me with the location of {buildname}, please?",
            f"I'm trying to find {buildname}, could you give me directions?",
            f"I'm searching for {buildname}, could you tell me how to get there?",
            f"Where can I go to find {buildname}?",
            f"Please could you assist me in finding {buildname}?",
            f"I'm trying to locate {buildname}, do you know which way I should go?",
            f"I need to find {buildname}, could you tell me where it is located?",
            f"Do you know where {buildname} is? If so, could you please tell me?",
            f"I'm trying to find {buildname}, any help would be appreciated.",
            f"I'm searching for {buildname}, any idea where I should start?",
            f"Where is {buildname} situated?",
            f"I'm trying to locate {buildname}, could you help me with its whereabouts?",
            f"I'm not sure where {buildname} is located, could you provide me with some guidance?",
            f"Can you please tell me where to find {buildname}?",
            f"I need to get to {buildname}, any idea how I could get there?",
            f"I'm hoping you could help me out, where exactly is {buildname}?",
            f"Could you give me directions to {buildname}, please?",
            f"Me find {buildname} where can?",
            f"Where {buildname} be at?",
            f"Tell me {buildname} place?",
            f"Place for {buildname} find kaise karu?",
            f"Where is {buildname} located?",
            f"Where me get {buildname} from?",
            f"Find {buildname} where to go?",
            f"Can you tell me where {buildname} is?",
            f"Where {buildname} find?",
            f"{buildname} dhoondhna hai kahan se milega?",
            f"Where {buildname} find karu?",
            f"{buildname} ki location batao?",
            f"Where {buildname} milta hai?",
            f"Tell {buildname} address?",
            f"Where {buildname} search karu?",
            f"Mujhe {buildname} kahan milega?",
            f"Kahan par hai {buildname}?",
            f"{buildname} ka pata kaise chalega?",
            f"{buildname} kahan pe milega?",
            f"{buildname} ki location batao?",
            f"{buildname} kis jagah par hai?",
            f"{buildname} kahan dhoondhoon?",
            f"{buildname} kahan se milega?",
            f"{buildname} ki jagah kahan hai?",
            f"{buildname} dhoondhne ke liye kahan jana hoga?",
            f"{buildname} kis address par hai?",
            f"{buildname} ka location kahan hai?",
            f"{buildname} ko kahan se dhoondhoon?",
            f"{buildname} kahan milta hai?",
            f"{buildname} ki exact location kya hai?"
        ],
        "responses": f"From Main Gate, {directions[i]}"
    }
    )

with open("Building_Dir.json", "w") as f:
    json.dump(data, f, indent=4)