import json

comp_list = [
    "Speed Programming",
    "User Interface/User Experience Competition",
    "Speed Debugging",
    "Web Development",
    "Database Design",
    "BlockChain Development",
    "Pseudowar",
    "Hackathon ",
    "Mobile Application Development",
    "Data Science ",
    "Capture the Flag ",
    "Game Development",
    "Code in the Dark",
    "Code Sprint",
    "Counter-Strike: GO ",
    "DOTA 2",
    "FIFA 23",
    "PUBG Mobile",
    "Tekken 7",
    "Counter-Strike 1.6",
    "Valorant",
    "Freefire",
    "Clash Royale",
    "Robo Race",
    "Robo Combat",
    "Robo Sumo",
    "Hardware Exhibition",
    "Circuit Soldering",
    "AutoCAD",
    "Bottle Rocket",
    "Drone Evaluation",
    "Robot Soccer",
    "Spud Gun",
    "Chess",
    "Parlimentary Debate",
    "Eat All You Can ",
    "IQuest",
    "Futsal Tournament",
    "Photography",
    "Reels",
    "Taboo",
    "Sketching and Painting",
    "Math Olympiad",
    "Human Ludo",
    "Maze",
]


rooms_list = [
    "Lab 1, Lab 2 (Round 1) and Lab 3, Lab 4 (Round 2)",
    "Lab 6",
    "Lab 1, Lab 2 (Round 1)",
    "Lab 3, Lab 4 (Round 1)",
    "C15, C16 (Round 1)",
    "E1, E2 (Round 1) and Lab 7 (Round 2)",
    "E1, E2",
    "A6, A7",
    "B10, B11",
    "Lab 7 (Round 1)",
    "... This competition will not place today",
    "B9",
    "Lab 10 (Round 1)",
    "... This competition will not place today",
    "Lab 5, Lab 8, FYP Lab",
    "Lab 5, Lab 8, FYP Lab",
    "EE Conference Room",
    "E3, E6, C22",
    "EE Conference Room",
    "Lab 5, Lab 8, FYP Lab",
    "Lab 5, Lab 8, FYP Lab",
    "E3, E6, C22",
    "C12",
    "CS Stairs",
    "BasketBall Ground",
    "BasketBall Ground",
    "Masjid Ground",
    "Electronic's Lab",
    "Lab 11 (Round 1 and Round 2)",
    "Masjid Ground",
    "EE Ground",
    "... This competition will not place today",
    "Masjid Ground",
    "D21",
    "A1, A8",
    "New Building",
    "4th Floor",
    "Futsal Court",
    "D22",
    "D22",
    "D23",
    "C20 and C21",
    "Lab 6 and Lab 10",
    "New Building (Round 1 and Round 2)",
    "Masjid Ground",
]
time_list_start = [
    "9:30AM (round 2)",
    "9:30AM (round 2)",
    "1AM (round 2)",
    "12PM (round 2)",
    "9:30AM (round 2)",
    "... The competition is not held today...",
    "9:30AM (round 2)",
    "9:30AM",
    "9:30AM (round 2)",
    "9:30AM (round 2)",
    "9:30AM",
    "9:30AM (round 2)",
    "9:30AM (round 2)",
    "... The competition is not held today...",
    "9:30AM",
    "9:30AM",
    "9AM",
    "9AM",
    "9:30AM",
    "9:30AM",
    "9:30AM",
    "9:30AM",
    "9:30AM",
    "1AM",
    "... The competition is not held today...",
    "9:30AM",
    "... The competition is not held today...",
    "9:30AM",
    "... The competition is not held today...",
    "... The competition is not held today...",
    "... The competition is not held today...",
    "9:30AM",
    "... The competition is not held today...",
    "9:30AM",
    "9:30AM",
    "... The competition is not held today...",
    "... The competition is not held today...",
    "9:30AM (round 2)",
    "9:30AM",
    "9:30AM",
    "9:30AM",
    "... The competition is not held today...",
    "12:30PM (round 2)",
    "9:30AM",
    "... The competition is not held today...",
]


time_list_end = [
    "12:30 (round 2)",
    "12:30 (round 2)",
    "4 (round 2)",
    "4 (round 2)",
    "12 (round 2)",
    "N/A",
    "1 (round 2)",
    "1:30",
    "1:30:00 AM (round 2)",
    "11:30 (round 2)",
    "3:30",
    "3:30 (round 2)",
    "11:30 (round 2)",
    "N/A",
    "3:30",
    "3:30",
    "3:30",
    "3:30",
    "3:30",
    "3:30",
    "3:30",
    "3:30",
    "3:30",
    "3:30",
    "N/A",
    "12",
    "N/A",
    "12",
    "N/A",
    "N/A",
    "N/A",
    "12",
    "N/A",
    "3:30",
    "3:30",
    "N/A",
    "N/A",
    "3:30 (round 2)",
    "3:30",
    "3:30",
    "3:30",
    "N/A",
    "3:30 (round 2)",
    "3:30",
    "N/A",
]


import json

# print(len(comp_list), len(rooms_list), len(time_list_start), len(time_list_end))

data = []
i = 0
for i in range(len(comp_list)):
    title = comp_list[i].replace(" ", "_")
    data.append(
        {
            "tag": f"{title}_time",
            "time_start": f"{time_list_start[i]}",
            "time_end": f"{time_list_end[i]}",
        },
    )
    data.append({"tag": f"{title}_venue", "venue_name": f"{rooms_list[i]}"})
    i = i + 1

with open("details_temp_10.json", "w") as f:
    json.dump(data, f, indent=4)
